CC = clang++

LDFLAGS = $(LDCOVERAGE_FLAGS) -lboost_system -pthread
CPPFLAGS = $(CCCOVERAGE_FLAGS) $(GLOBAL_CPP_FLAGS)

INCLUDE = -I$(INCLUDE_TOP) -I$(INCLUDE_CORE_TOP) -I$(INCLUDE_CORE_CONSTANTS) \
		  -I$(INCLUDE_CORE_INSTRUCTIONS) -I$(INCLUDE_CORE_INTERFACES) -I$(INCLUDE_COMMONS_TOP) -I$(INCLUDE_EMULATOR_TOP) \
		  -I$(INCLUDE_DEBUGGER_TOP) -I$(INCLUDE_DEBUGGER_INTERFACES) -I$(INCLUDE_DEBUGGER_PROTOCOL) -I$(INCLUDE_EMULATOR_RUNTIME) \
		  -I$(INCLUDE_DEBUGGER_TRANSPORT) -I$(INCLUDE_DEBUGGER_INPUT)

DEP_FILES = $(BUILD_TEMP)/gbxdb_cli.d

TARGET_SOURCE = gbxdb_cli.cc
TARGET =  $(CLI_DEBUGGER)

all: $(TARGET)

-include $(DEP_FILES)
$(TARGET): $(TARGET_SOURCE) $(COMMONS_LIB) $(DEBUG_LIB)
	$(CC) -MMD -MT"$@" -MF"$(DEP_FILES)" $(INCLUDE) $(TARGET_SOURCE) $(CPPFLAGS) -o $(TARGET) $(COMMONS_LIB) $(DEBUG_LIB) $(LDFLAGS)