CC = clang++

LDFLAGS = $(LDCOVERAGE_FLAGS) -lboost_system -pthread
CPPFLAGS = $(CCCOVERAGE_FLAGS) $(GLOBAL_CPP_FLAGS)

INCLUDE = -I$(INCLUDE_COMMONS_TOP)

DEP_FILES = $(BUILD_TEMP)/gbxdb_cli.d

TARGET_SOURCE = gbxdb_cli.cc
TARGET =  $(CLI_DEBUGGER)

all: $(TARGET)

-include $(DEP_FILES)
$(TARGET): $(TARGET_SOURCE) $(COMMONS_LIB)
	$(CC) -MMD -MT"$@" -MF"$(DEP_FILES)" $(INCLUDE) $(TARGET_SOURCE) $(CPPFLAGS) -o $(TARGET) $(COMMONS_LIB) $(LDFLAGS)