#include "AddressingModeFormat.h"

namespace gbxcore
{
    
AddressingModeFormat AddressingModeTemplate::NoAddressingMode                          
                                                                    {.acquireOperand1 = false,
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::RegisterAddressingMode                          
                                                                    {.acquireOperand1 = false,
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::ImmediateAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = true,  
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };
AddressingModeFormat AddressingModeTemplate::SingleImmediatePairAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = true,  
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::RegisterIndexedSourceAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = true,  
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = true, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = true, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::RegisterIndexedDestinationAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = true,  
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = true, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::RegisterIndirectSourceAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = true, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::RegisterIndirectDestinationAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = true, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::RegisterExtendedSourceAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = true,  
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = true, 
                                                                        .acquireOperand2FromPc = true, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = true, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::RegisterExtendedDestinationAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = true,  
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = true, 
                                                                        .acquireOperand2FromPc = true, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = true,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::ImmediateRegisterIndirectAddressingMode 
                                                                {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = true,  
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = true, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };
                                                                        
AddressingModeFormat AddressingModeTemplate::ImmediateRegisterIndirectSourceIncrementAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = true, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = true,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::ImmediateRegisterIndirectSourceDecrementAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = true, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = true,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::ImmediateRegisterIndirectDestinationIncrementAddressingMode                          
                                                                    {.acquireOperand1 = false, 
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = true,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = true, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::ImmediateRegisterIndirectDestinationDecrementAddressingMode                          
                                                                    {.acquireOperand1 = false, 
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = true,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = true, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };
                                                                        

AddressingModeFormat AddressingModeTemplate::ImplicitRegisterSourceAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = true,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };


AddressingModeFormat AddressingModeTemplate::ImplicitRegisterDestinationAddressingMode                          
                                                                    {.acquireOperand1 = false,
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = true,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::ImplicitImmediateSourceAddressingMode                          
                                                                    {.acquireOperand1 = true,
                                                                        .acquireOperand1FromPc = true, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = true, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = true,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::ImplicitImmediateDestinationAddressingMode
                                                                    {.acquireOperand1 = true,
                                                                        .acquireOperand1FromPc = true, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = true,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::ImmediatePairAddressingMode
                                                                    {.acquireOperand1 = true,
                                                                        .acquireOperand1FromPc = true, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = true, 
                                                                        .acquireOperand2FromPc = true, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::RegisterPairAddressingMode
                                                                    {.acquireOperand1 = false,
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::RegisterIndirectSourceAndDestinationAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = true, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = true, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::RegisterIndirectDestinationPair
                                                                    {.acquireOperand1 = false, 
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = true,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::RegisterIndirectSourcePair
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = true, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = true,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = true, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand2Directly = true,
                                                                        .incrementSourceOperand2 = true,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };

AddressingModeFormat AddressingModeTemplate::ExtendedDestinationPair
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = true, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = true, 
                                                                        .acquireOperand2FromPc = true, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = false,
                                                                        .writeBackPairAtImmediateAddress = true
                                                                        };

AddressingModeFormat AddressingModeTemplate::SubRoutineCallMode 
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = true, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = true, 
                                                                        .acquireOperand2FromPc = true, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand2Directly = false,
                                                                        .incrementSourceOperand2 = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        .writeBackPairAtRegisterAddress = true,
                                                                        .writeBackPairAtImmediateAddress = false
                                                                        };                                                    
}