#include "AddressingModeFormat.h"

namespace gbx
{
    
const AddressingModeFormat AddressingModeTemplate::NoAddressingMode                          
                                                                    {.acquireOperand1 = false,
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        };

const AddressingModeFormat AddressingModeTemplate::RegisterAddressingMode                          
                                                                    {.acquireOperand1 = false,
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        };

const AddressingModeFormat AddressingModeTemplate::ImmediateAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = true,  
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        };

const AddressingModeFormat AddressingModeTemplate::RegisterIndexedSourceAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = true,  
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = true, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = true, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        };

const AddressingModeFormat AddressingModeTemplate::RegisterIndexedDestinationAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = true,  
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = true, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        };

const AddressingModeFormat AddressingModeTemplate::RegisterIndirectSourceAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = true, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        };

const AddressingModeFormat AddressingModeTemplate::RegisterIndirectDestinationAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = true, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        };

const AddressingModeFormat AddressingModeTemplate::RegisterExtendedSourceAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = true,  
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = true, 
                                                                        .acquireOperand2FromPc = true, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = true, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        };

const AddressingModeFormat AddressingModeTemplate::RegisterExtendedDestinationAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = true,  
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = true, 
                                                                        .acquireOperand2FromPc = true, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = true,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        };

const AddressingModeFormat AddressingModeTemplate::ImmediateRegisterIndirectAddressingMode 
                                                                {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = true,  
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = true, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        };
                                                                        
const AddressingModeFormat AddressingModeTemplate::ImmediateRegisterIndirectSourceIncrementAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = true, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = true,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        };

const AddressingModeFormat AddressingModeTemplate::ImmediateRegisterIndirectSourceDecrementAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = true, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = true,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        };

const AddressingModeFormat AddressingModeTemplate::ImmediateRegisterIndirectDestinationIncrementAddressingMode                          
                                                                    {.acquireOperand1 = false, 
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = true,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = true, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        };

const AddressingModeFormat AddressingModeTemplate::ImmediateRegisterIndirectDestinationDecrementAddressingMode                          
                                                                    {.acquireOperand1 = false, 
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = true,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = true, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        };
                                                                        

const AddressingModeFormat AddressingModeTemplate::ImplicitRegisterSourceAddressingMode                          
                                                                    {.acquireOperand1 = true, 
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = true,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        };


const AddressingModeFormat AddressingModeTemplate::ImplicitRegisterDestinationAddressingMode                          
                                                                    {.acquireOperand1 = false,
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = true,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        };

const AddressingModeFormat AddressingModeTemplate::ImplicitImmediateSourceAddressingMode                          
                                                                    {.acquireOperand1 = true,
                                                                        .acquireOperand1FromPc = true, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = true, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = true,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false,
                                                                        };

const AddressingModeFormat AddressingModeTemplate::ImplicitImmediateDestinationAddressingMode
                                                                    {.acquireOperand1 = true,
                                                                        .acquireOperand1FromPc = true, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = true, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = true
                                                                        };

const AddressingModeFormat AddressingModeTemplate::ImmediatePairAddressingMode
                                                                    {.acquireOperand1 = true,
                                                                        .acquireOperand1FromPc = true, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = true, 
                                                                        .acquireOperand2FromPc = true, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false
                                                                        };

const AddressingModeFormat AddressingModeTemplate::RegisterPairAddressingMode
                                                                    {.acquireOperand1 = false,
                                                                        .acquireOperand1FromPc = false, 
                                                                        .acquireOperand1Directly = false, 
                                                                        .incrementDestination = false,
                                                                        .decrementDestination = false,
                                                                        .incrementSource = false,
                                                                        .decrementSource = false,
                                                                        .acquireOperand1Implicitly = false,
                                                                        .acquireOperand2 = false, 
                                                                        .acquireOperand2FromPc = false, 
                                                                        .acquireOperand2AtComposedAddress = false, 
                                                                        .acquireOperand2Implicitly = false,
                                                                        .acquireOperand3 = false, 
                                                                        .writeBack = false, 
                                                                        .writeBackAtOperandAddress = false, 
                                                                        .writeBackAtRegisterAddress = false, 
                                                                        .writeBackAtComposedOperandAddress = false,
                                                                        .writeBackAtImplicitlyWithRegister = false,
                                                                        .writeBackAtImplicitlyWithImmediateOperand = false
                                                                        };

}